[package]
name = "tokio-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
ctapi-rs = { path = "../../ctapi-rs", features = ["tokio-support"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
